"""add author to documents

Revision ID: 5bda16581ff6
Revises: 40022ec242e2
Create Date: 2026-04-09 22:12:26.425175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bda16581ff6'
down_revision: Union[str, None] = '40022ec242e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'author')
    # ### end Alembic commands ###
